### PR TITLE
updated example3 of tabs with correct format and correct name

### PR DESCRIPTION
**Pull request by shreedharshetty**
following example3 will not set active class on 3rd tab, so changing the format with right tab name

### CODE REVIEW

**Comment by shreedharshetty** [comment]
@ClickerMonkey Any updates on this?

**Comment by ClickerMonkey** [comment]
@shreedharshetty Not sure I follow, the example is working fine. The `active` attribute is meant to be a binding to a scoped variable so you can determine or change the currently selected tab. Your commit sets it to be a constant string which makes the example confusing. Maybe I'm missing something?

**Comment by shreedharshetty** [comment]
@ClickerMonkey  if you look at other examples it sets active class to tab by looking at what name is been passed to `active`. atleast when i tried copying your example code, it didn't set the active class, so thought of creating a pr for the same. it was lil confusing by referring to other examples where you pass name. model3 scoped variable is created here - https://github.com/ClickerMonkey/SemanticUI-Angular/blob/master/src/tab/examples.html#L23

let us put a doc comment saying model3 is a scoped variable? couldn't get it at a first stare :)

i will close this pull request.

**Comment by ClickerMonkey** [comment]
I agree, the examples should also show the JS so you get the full picture! Thanks for the constructive feedback.

**Pull request closed without merging**
